### ISSUE TITLE
sqlalchemy version bug

### ISSUE THREAD

**Issue by rusu24edward** [ABM4ALL/Melodie#10]
Following from #3, #4, and #6, the code must be updated to handle the sqlalchemy version issue. Ideally, the code can work with the newest version of the dependency. This is not always possible, especially if it requires more than trivial changes to the code, so at the very least the requirements and setup file need to be updated to reflect the dependency on version 1.4.41

**Comment by hzyrc6011** [comment]
Thanks for reporting this problem, the version constraint has been already added.
