### ISSUE TITLE
run_analyzer not clear

### ISSUE THREAD

**Issue by rusu24edward** [ABM4ALL/Melodie#11]
In the covid contagion tutorial, I get the following output from `run_simulator.py`:
```
db.py:127 INFO Database contains tables: ['ID_AgeGroup', 'ID_HealthState', 'Parameter_AgeGroup_TransitionProb', 'Parameter_AgentParams', 'agents_result', 'environment_result', 'simulator_scenarios'].
db.py:131 INFO Database drops tables: ['ID_AgeGroup', 'ID_HealthState', 'Parameter_AgeGroup_TransitionProb', 'Parameter_AgentParams', 'agents_result', 'environment_result', 'simulator_scenarios'].
simulator.py:169 INFO Simulation started - id_scenario = 0, id_run = 0
simulator.py:221 INFO Simulation completed - id_scenario = 0, id_run = 0
    model-setup          0.041s
    model-run            0.09s
    data-collect         1.498s

simulator.py:169 INFO Simulation started - id_scenario = 1, id_run = 0
simulator.py:221 INFO Simulation completed - id_scenario = 1, id_run = 0
    model-setup          0.041s
    model-run            0.07s
    data-collect         1.55s

simulator.py:169 INFO Simulation started - id_scenario = 1, id_run = 1
simulator.py:221 INFO Simulation completed - id_scenario = 1, id_run = 1
    model-setup          0.04s
    model-run            0.074s
    data-collect         1.563s

simulator.py:257 INFO Simulator completed, time elapsed 5.145s.
```

I run `run_analyzer.py`, which generates files in the `/data/output` directory. It is not clear from the tutorial what is supposed to happen with `run_analyzer`, so please update for clarity.

**Comment by SongminYu** [comment]
Hi @rusu24edward, thanks for your comment! We added one more paragraph explaining the ``analyzer.py`` function. You can find the paragraph in the [DataCollection](https://abm4all.github.io/Melodie/html/tutorial.html#datacollector) section of the tutorial as below. Please let us know if further revision is needed, or you could close this issue. Thanks!

The added paragraph:

In the example project, we also prepared a simple ``analyzer.py`` file that produces two figures based on the results showing the population of different ``health_state``. The two figures will be saved in the ``data/output`` folder together with the ``.sqlite`` file. Similarly, users can also define other post-processing functions in the ``analyzer.py`` file.
