### ISSUE TITLE
python versioning should be consistent

### ISSUE THREAD

**Issue by rusu24edward** [ABM4ALL/Melodie#17]
In some places you have updated the instructions to use python 3.8+, but others you have not. Here's what I was able to locate in the repo:

- [x] [Here](https://github.com/ABM4ALL/Melodie/blob/master/setup.py#L135) you should not have version of python less than 3.8.
- [x] [Here](https://github.com/ABM4ALL/Melodie/blob/master/setup.py#L165) should have version required >= 3.8
- [x] [Here](https://github.com/ABM4ALL/Melodie/blob/master/requirements.txt#L20) should show >= 3.8
- [x] I don't think you need [this line](https://github.com/ABM4ALL/Melodie/blob/master/build_requirements.txt#L1) anymore
- [x] I don't think you need [this line](https://github.com/ABM4ALL/Melodie/blob/master/.travis.yml#L4) anymore

**Comment by SongminYu** [comment]
Hi @rusu24edward, thanks for your detailed check of our project! We have fixed these lines. Thanks!
