### ISSUE TITLE
melodie_simplification

### ISSUE THREAD

**Issue by SongminYu** [ABM4ALL/Melodie#25]
- `register_dataframe` and `load_dataframe` and `load_matrix` go to `Scenario`, which also holds the registered tables. Then, before `setup`, users also need to inherit `load`. 
- `id_run` becomes a hidden attribute of `scenario`, like `scenario.id`. So the users can save `id_run` when using customized functions for collecting&saving data. The model is run for each `scenario` and `id_run`.
- In the new interfaces `scenario.load_dataframe()` and `scenario.load_dataframe()`, we use `string` as input parameter type (with .xlsx), which is the file name. `DataFrameInfo` and `MatrixInfo` classes are not required. We import the file by path directly.
- Remove the dependency on the `.sqlite` database and switch to `.xlsx` and `.csv` files.
  - Using another software to open `.sqlite` files is always a barrier. 
  - Users can choose from `.xlsx` and `.csv` as the format of `Result_Environment` and `Result_Agents`.
    - By default, we suggest `.csv`.
    - The user can call `data_collector.set_format("Result_Environment", "excel")` to change it to `.xlsx`.
   - For this, we need to make changes in the following places:
     - when loading data, we don't save to `.sqlite` directly.
     - `DBConn` 
     - `create_db_conn(self.config).clear_database()` in `BaseModellingManager`
 - To be aligned with `tab2dict`, I also changed the convention of the table names, as you can see: `Result_Environment` and `Result_Agents`.

**Comment by hzyrc6011** [comment]
1. As excel is slower than CSV, and when appending, we should read the full file. So I think using the only format `csv` might be enough.

**Comment by SongminYu** [comment]
- `data_collector` should be able to use `config`. 
- `agent.py` Line 15: the assert does not allow `run_id` to be included in the `agent_params`. We should allow this.

**Comment by SongminYu** [comment]
The `id_run` is initialized after `_setup()`. So, when calling `setup_data()`, it is still `-1`.

![image](https://github.com/ABM4ALL/Melodie/assets/16057131/e0a99e8c-8057-4c43-906c-2710804dead9)

**Comment by SongminYu** [comment]
add a new function `save_dataframe` in DataCollector functioning like this:

<img width="911" alt="Screenshot 2024-01-28 at 14 37 25" src="https://github.com/ABM4ALL/Melodie/assets/16057131/fa5a62ed-7284-43d8-8996-d13b86cd4a26">

**Comment by SongminYu** [comment]
The revisions are done and published in v1.0.0. This issue is closed.
