### ISSUE TITLE
developer installation documentation needs install Melodie

### ISSUE THREAD

**Issue by rusu24edward** [ABM4ALL/Melodie#9]
The installation [instructions for the developer](https://abm4all.github.io/Melodie/html/installation.html#developer-installation) needs a line for installing Melodie into the virtual environment, probably something like `pip3 install -e . --no-deps`.

**Comment by hzyrc6011** [comment]
@rusu24edward  Thanks for this report, the bug has been fixed in the newer version 
https://abm4all.github.io/Melodie/html/installation.html
